services:
  nginx:
    container_name: nginx
    build: requirements/nginx 
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress
      - redis
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    networks:
      - inception
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
  
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
  
  portfolio:
    container_name: portfolio
    build: requirements/bonus/portfolio
    ports:
      - 8080:8080
    networks:
      - inception
    restart: always

  redis:
    container_name: redis
    build: requirements/bonus/redis
    ports:
      - 6379:6379
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/wordpress

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb
