services:
  nginx:
    container_name: nginx
    build: requirements/nginx 
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress
      - redis
      - adminer
    restart: always
    volumes:
      - wordpress:/var/www/html
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    networks:
      - inception
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
  portfolio:
    container_name: portfolio
    build: requirements/bonus/portfolio
    ports:
      - 8080:8080
    networks:
      - inception
    restart: always
  redis:
    container_name: redis
    build: requirements/bonus/redis
    ports:
      - 6379:6379
    networks:
      - inception
    depends_on:
      - wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
  ftp:
    container_name: ftp
    build: requirements/bonus/ftp
    ports:
      - 21:21
      - "21100-21110:21100-21110"
    networks:
      - inception
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
  adminer:
    container_name: adminer
    build: requirements/bonus/adminer
    networks:
      - inception
    restart: always
    volumes:
      - wordpress:/var/www/html/
    depends_on:
      - mariadb
  portainer:
    container_name: portainer
    build: requirements/bonus/portainer
    ports:
      - 9000:9000
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  inception:
    driver: bridge
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mariadb
  portainer:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/portainer